# Font
font_family      JetBrains Mono Nerd Font
font_size 13.0

# Cursor
cursor_shape block
cursor_trail 1

disable_ligatures never
enable_audio_bell no

# Padding (why weird value? consistency with foot)
window_margin_width 21.75

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell fish
shell_integration no-cursor

# Copy
map ctrl+c    copy_or_interrupt

window_padding_width 27
cursor_blink_interval 0
background_opacity 0.65
confirm_os_window_close 0

sync_to_monitor no
