theme {
    # Replace with the path to your chosen .colors file
    color_scheme = /usr/share/color-schemes/BreezeDark.colors

    # Common widget styles
    style = Fusion

    icon_theme = Papirus-Dark
    font = Sans Serif
    font_size = 11
}
