plugin  {
        dynamic-cursor = {
            enabled = true
            shaperule = text, rotate:offset: 90

            shaperule = grab, stretch, stretch:limit: 2000

            shaperule = clientside, none
        }
}
